### PR TITLE
Fix using query.notContainedIn and query.doesNotMatchQuery at the same time, notContainedIn will be ignored problem 

### LINKED ISSUE #798: Using query.notContainedIn and query.doesNotMatchQuery at the same time, notContainedIn will be ignored

### PR DESCRIPTION
**Pull request by carmenlau**
Fix #798, the root cause of the problem is the replace query function in `RestQuery` will overwrite the `$in` and `$nin` field.

### CODE REVIEW

**Comment by flovilmart** [comment]
Could you add tests that exemplify the fix?

File: src/RestQuery.js [hunk 1]
```diff
@@ -290,7 +298,11 @@ RestQuery.prototype.replaceSelect = function() {
       values.push(result[selectValue.key]);
     }
     delete selectObject['$select'];
-    selectObject['$in'] = values;
+    if (Array.isArray(selectObject['$in'])) {
```
Comment (flovilmart) [inline src/RestQuery.js]: you ca simplify with selectObject['$in'] = [].concat(selectObject['$in'] || [], values);
