### PR TITLE
Fixes bug related to subqueries on unfetched objects

### LINKED ISSUE #1014: matchesQuery on relation query always finds zero objects
#### Environment Setup
parse-server 2.1.6, Heroku, MongoLab, iOS SDK 1.12.0

#### Steps to reproduce
```
var relationQuery = object.relation("relationKey").query();
var anotherQuery = new Parse.Query(Class);
anotherQuery.matchesQuery("key", relationQuery);
anotherQuery.find(); //Always finds 0 objects
```

This works correctly in hosted Parse. I also manually double-checked the db and can confirm this should find more than zero objects.

#### Logs/Trace
This error is showing up on the iOS side. May or may not be related:
` [Error]: Response status code was unacceptable: 403 (Code: 1, Version: 1.12.0)`

### PR DESCRIPTION
**Pull request by flovilmart**
fixes #1014

### CODE REVIEW

File: src/RestQuery.js [hunk 1]
```diff
@@ -246,15 +248,19 @@ RestQuery.prototype.replaceNotInQuery = function() {
...
     this.config, this.auth, notInQueryValue.className,
-    notInQueryValue.where);
+    notInQueryValue.where, additionalOptions);
   return subquery.execute().then((response) => {
     var values = [];
     for (var result of response.results) {
       values.push({
         __type: 'Pointer',
-        className: notInQueryValue.className,
+        className: subquery.className,
```
Comment (flovilmart) [inline src/RestQuery.js]: use the subquery.className as it may have been mutated by redirectClassNameForKey
