### PR TITLE
Makes HTTPResponse serializable

### LINKED ISSUE #2033: Parse.cloud.httpRequest buffer
### Issue Description

Hi everyone,

I'm using a third party REST API from my cloudcode.

For some requests, everything works great just like on parse.com.

example : api.server.com/1/createuser return a data array with everything. I can get httpResponse.data.id to get the new user id.

But for other ones, Parse.cloud.httpRequest returns a buffer instead of the data array.
example : api.server.com/1/createdoc return an empty buffer so I can't get httpResponse.data.id to get the new created document id. (request is working, new doc is created)
Of course, this request is working on parse.com

Someone knows what is the problem ? How to solve this ?

Thanks

### Steps to reproduce

Example of my query

```
return Parse.Cloud.httpRequest({
            method: 'POST',
            url: this._api.endPoint + '/users/documents/',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'Basic ' + this._api.auth
            },
            body: {
                Type: type
            }
        });
```

#### Expected Results

httpResponse.data.id

#### Actual Outcome

empty httpResponse.buffer

### Environment Setup

- **Server**
  - parse-server version: last
  - Operating System:     last debian
  - Hardware:             2 x86 64bit Cores/2GB Memory
  - Localhost or remote server? remote server

- **Database**
  - MongoDB version: last

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

parse-server-1 | 2016-06-11T15:30:19.041283837Z verbose: POST /parse/functions/createDoc { host: 'api.myparseserver.com:1337',
parse-server-1 | 2016-06-11T15:30:19.041375779Z   connection: 'keep-alive',
parse-server-1 | 2016-06-11T15:30:19.041396992Z   'content-length': '282',
parse-server-1 | 2016-06-11T15:30:19.041415549Z   'x-devtools-emulate-network-conditions-client-id': '’,
parse-server-1 | 2016-06-11T15:30:19.041433814Z   origin: 'file://',
parse-server-1 | 2016-06-11T15:30:19.041452010Z   'user-agent': 'Mozilla/5.0 (Linux; Android 6.0.1; ONE A2003 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36',
parse-server-1 | 2016-06-11T15:30:19.041471028Z   'content-type': 'text/plain',
parse-server-1 | 2016-06-11T15:30:19.041488502Z   accept: '*/*',
parse-server-1 | 2016-06-11T15:30:19.041527490Z   'accept-encoding': 'gzip, deflate',
parse-server-1 | 2016-06-11T15:30:19.041546639Z   'accept-language': 'fr-FR,en-US;q=0.8',
parse-server-1 | 2016-06-11T15:30:19.041564072Z   'x-requested-with': 'com.myapp.app2' } {
parse-server-1 | 2016-06-11T15:30:19.041581647Z   "type": "MYTYPE"
parse-server-1 | 2016-06-11T15:30:19.041599392Z }
parse-server-1 | 2016-06-11T15:30:19.292721015Z REQ OK
parse-server-1 | 2016-06-11T15:30:19.301017362Z verbose: {
parse-server-1 | 2016-06-11T15:30:19.301143740Z   "response": {
parse-server-1 | 2016-06-11T15:30:19.301174849Z     "result": {
parse-server-1 | 2016-06-11T15:30:19.301194959Z       "status": 200,
parse-server-1 | 2016-06-11T15:30:19.301213155Z       "headers": {
parse-server-1 | 2016-06-11T15:30:19.301231470Z         "cache-control": "no-cache",
parse-server-1 | 2016-06-11T15:30:19.301249657Z         "pragma": "no-cache",
parse-server-1 | 2016-06-11T15:30:19.301290570Z         "content-type": "application/json; charset=utf-8",
parse-server-1 | 2016-06-11T15:30:19.301309057Z         "expires": "-1",
parse-server-1 | 2016-06-11T15:30:19.301326620Z         "server": "thirdpartyAPIServer »,
parse-server-1 | 2016-06-11T15:30:19.301344125Z         "date": "Sat, 11 Jun 2016 15:30:19 GMT",
parse-server-1 | 2016-06-11T15:30:19.301361578Z         "connection": "close",
parse-server-1 | 2016-06-11T15:30:19.301378842Z         "content-length": "170"
parse-server-1 | 2016-06-11T15:30:19.301396056Z       },
parse-server-1 | 2016-06-11T15:30:19.301412717Z       "buffer": {
parse-server-1 | 2016-06-11T15:30:19.301430141Z         "type": "Buffer",
parse-server-1 | 2016-06-11T15:30:19.301447586Z         "data": []
parse-server-1 | 2016-06-11T15:30:19.301464748Z       }
parse-server-1 | 2016-06-11T15:30:19.301481681Z     }
parse-server-1 | 2016-06-11T15:30:19.301538854Z   }
parse-server-1 | 2016-06-11T15:30:19.301557071Z }

### PR DESCRIPTION
**Pull request by flovilmart**
Fixes #2033

response.body don't seem to be set in some cases, and was never specified in the node.js docs.

This change rely on the `body` parameter from the response callback.

Also, the getters have been replaced by ES5 definedProperty calls to make them enumerable so they play nice with serializers.
This change also does a bit of type inference in order to properly handle all body types (string, buffer and JSON)

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
@flovilmart updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@flovilmart updated the pull request.

**Comment by facebook-github-bot-2** [comment]
@flovilmart updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@flovilmart updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@flovilmart updated the pull request.

**Comment by cleever** [comment]
Great job @flovilmart. 
Thank you for your attention!

**Comment by facebook-github-bot-8** [comment]
@flovilmart updated the pull request.

File: src/cloud-code/HTTPResponse.js [hunk 1]
```diff
@@ -1,21 +1,49 @@
...
+    } else if (Buffer.isBuffer(body)) {
+      this.buffer = body;
+    } else if (typeof body == 'object') {
+      _data = body;
+    }
+
+    let getText = () => {
+      if (!_text && this.buffer) {
+          _text = this.buffer.toString('utf-8');
+        } else if (!_text && _data) {
```
Comment (TylerBrock) [inline src/cloud-code/HTTPResponse.js]: indent looks off here

File: src/cloud-code/HTTPResponse.js [hunk 2]
```diff
@@ -1,21 +1,49 @@
...
+          _text = JSON.stringify(_data);
+        }
+        return _text; 
     }
-    return this._data;
+
+    let getData = () => {
+      if (!_data) {
+          try {
```
Comment (TylerBrock) [inline src/cloud-code/HTTPResponse.js]: also here

**Comment by TylerBrock** [comment]
Looks great, i had two nits about whitespace but other than that shipit! :shipit:

**Comment by facebook-github-bot-8** [comment]
@flovilmart updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@flovilmart updated the pull request.

**Comment by cleever** [comment]
Great job guys. Thank you for merging so quickly.
