### PR TITLE
Cache users by objectID, and clear cache when updated via master key (fixes #1836)

### LINKED ISSUE #1836: request.user is not up-to-date
I have a simple Cloud Function:

```
Parse.Cloud.define('testQuery', function(request, response) {
    var user = request.user;
    response.success("user.get('data') = " + user.get('data'));
});
```

And a simple function call from Android SDK:

```
ParseCloud.callFunctionInBackground("testQuery", new HashMap<String, Object>(), new FunctionCallback<String>() {
    @Override
    public void done(String result, ParseException e) {
        if (e == null) {
            Log.d("testQuery", result);
        }
    }
});
```

Let's say the value "data" of my User object is "AAA". I call the function from Android SDK. Parse.com's server and self-hosted server both return `user.get('data') = AAA`.

Now I change the value of "data" to "BBB" from Dashboard, and call the function again. The results are different. Parse.com's server returns `user.get('data') = BBB` as expected, but the self-hosted server still returns `user.get('data') = AAA`.

Is it a correct behavior of the new Parse-Server or is it a bug? And if it's a correct behavior, how can I get the up-to-date data of request.user. Thanks.

### PR DESCRIPTION
**Pull request by drew-gross**
Previously users were cached by session token, which doesn't work when using master key to update a user, as we don't know the session token, and would have to do an extra query to get it. This caches by objectId so that they user cache can be cleared when the user is updated via master key.

### CODE REVIEW

**Comment by blacha** [comment]
Where do we actually query this? if you change the put key, you will need to change the get key?

**Comment by drew-gross** [comment]
Oh yeah good point. We should probably have a test to ensure that the cache actually gets used..

**Comment by facebook-github-bot-9** [comment]
@drew-gross updated the pull request.

File: src/RestWrite.js [hunk 1]
```diff
@@ -318,10 +318,22 @@ RestWrite.prototype.transformUser = function() {
...
-    cacheAdapter.user.del(this.auth.user.getSessionToken());
+  if (this.query) {
+    // If we're updating a _User object, clear the user cache for the session
+    if (this.auth.user && this.auth.user.getSessionToken()) {
+      this.config.cacheController.user.del(this.auth.user.getSessionToken());
+    } else {
+      // Update was made with master key, so we don't have the session. Query to find it. Hopefully we can make this faster later, somehow.
+      let userObject = Parse.Object.createWithoutData('_User', this.data.objectId);
+      let sessionsQuery = new Parse.Query('_Session');
+      //sessionsQuery.equalTo('user', userObject);
```
Comment (steven-supersolid) [inline src/RestWrite.js]: Should this line be commented out? Seems like there are no constraints on the query?

Comment (drew-gross) [inline src/RestWrite.js]: Nope I'm still working on this PR. The original issue was when a user was updated via master key, but the same issue will show up if the user is updated via one session token and the read via a different one. I'll mark is as WIP.

**Comment by facebook-github-bot-3** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-8** [comment]
@drew-gross updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@drew-gross updated the pull request.

**Comment by drew-gross** [comment]
@blacha this PR is finished now.

**Comment by blacha** [comment]
looks good to me.
