### PR TITLE
Fix null pointer includes

### LINKED ISSUE #2189: TypeError: Cannot read property '__type' of null
### Issue Description

While performing a query through the REST API:

```
curl 'http://$IP:1337/parse/classes/SectionItem' --data-binary '{"where":
{"$relatedTo":{"object" {"__type":"Pointer","className":"Class","objectId":"uAgTxj5kIt"},"key":"items"}},
"include":"<lots and lots of nested classes>"
```

 I get the following response:

```
Uncaught internal server error. [TypeError: Cannot read property '__type' of null] TypeError: Cannot read property '__type' of null
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:778:15)
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:753:32)
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:788:10)
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:788:10)
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:753:32)
    at includePath (/usr/lib/node_modules/parse-server/lib/RestQuery.js:644:18)
    at RestQuery.handleInclude (/usr/lib/node_modules/parse-server/lib/RestQuery.js:625:22)
    at /usr/lib/node_modules/parse-server/lib/RestQuery.js:630:22
    at run (/usr/lib/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/lib/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
```

I think this could be due to missing pointers

### Environment Setup

- **Server**
  - parse-server version: 2.2.15
  - Operating System:     Debian 8.5
  - Localhost or remote server?: DigitalOcean

- **Database**
  - MongoDB version: 3.0.11
  - Localhost or remote server?: ObjectRocket

### PR DESCRIPTION
**Pull request by flovilmart**
Fixes #2189

### CODE REVIEW

File: src/RestQuery.js [hunk 1]
```diff
@@ -564,15 +567,15 @@ function findPointers(object, path) {
 function replacePointers(object, path, replace) {
   if (object instanceof Array) {
     return object.map((obj) => replacePointers(obj, path, replace))
-              .filter((obj) => obj != null && obj != undefined);
+             .filter((obj) => typeof obj !== 'undefined');
```
Comment (flovilmart) [inline src/RestQuery.js]: strip out undefined, and keep the nulls to match parse.com behaviour

**Comment by facebook-github-bot-4** [comment]
@flovilmart updated the pull request - [view changes](https://github.com/ParsePlatform/parse-server/pull/2657/files/ed784e24e0c0a38a6c2e1a158028d975a34c8fe6..e769e2b28fd819efaa7b6fd3d1d8461b2b539a8b)

**Comment by doender** [comment]
👍
