### PR TITLE
Close client connections on SIGINT/SIGTERM

### LINKED ISSUE #2875: Server doesn't shut down with Ctrl+C
~~When using parse server with the Postgres database adapter,~~ the server doesn't shut down when `CTRL+C` is pressed.

### Steps to reproduce

1. Start parse server: 
  
  ```
  parse-server --appId a --masterKey m --databaseURI postgres://username:password@localhost:5432/db-name
  ```
2. Start parse dashboard and point it to this 

  ```
  parse-dashboard --appId a --masterKey m --serverURL http://localhost:1337/parse
  ```
3. Open the parse dashboard in a browser (`http://localhost:4040/apps`)
4. Stop parse dashboard (this step isn't necessary)
5. Try to stop parse server by pressing `CTRL+C` in the terminal where it was started.

#### Expected Results

Parse server stops

#### Actual Outcome

The following message is displayed and the server hangs:

```
Termination signal received. Shutting down.
```

If `CTRL+C` is pressed repeatedly (about 10-12 times), the following message is displayed:

```
(node:32165) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
```

Note that if parse dashboard isn't used, `CTRL+C` works as expected and parse server shuts down.

### Environment Setup

- **Server**
  - parse-server version : commit de36d9640bbfdc4a36d32db5f11e9be1044ae91a on master
  - Operating System:     Linux Mint 17.3
  - Hardware:             amd64
  - Localhost or remote server? localhost

Note: this issue is also present when using the release 2.2.22. However, with this release, some code has to be modified to use the Postgres adapter.

- **Database**
  - Postgres version: 9.5/9.6
  - MongoDB: 3.2.10
  - Hardware:        linux amd64
  - Localhost or remote server? localhost

### Logs/Trace

```
appId: a
masterKey: ***REDACTED***
port: 1337
databaseURI: postgres://username:password@localhost:5432/parse-test
mountPath: /parse
maxUploadSize: 20mb
verbose: 1
serverURL: http://localhost:1337/parse

[32517] parse-server running on http://localhost:1337/parse
verbose: REQUEST for [GET] /parse/serverInfo: {} method=GET, url=/parse/serverInfo, host=localhost:1337, connection=keep-alive, content-length=140, origin=http://localhost:4040, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:4040/apps, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.8, 
verbose: RESPONSE from [GET] /parse/serverInfo: {
  "response": {
    "features": {
      "globalConfig": {
        "create": true,
        "read": true,
        "update": true,
        "delete": true
      },
      "hooks": {
        "create": false,
        "read": false,
        "update": false,
        "delete": false
      },
      "cloudCode": {
        "jobs": true
      },
      "logs": {
        "level": true,
        "size": true,
        "order": true,
        "until": true,
        "from": true
      },
      "push": {
        "immediatePush": true,
        "scheduledPush": false,
        "storedPushData": true,
        "pushAudiences": false
      },
      "schemas": {
        "addField": true,
        "removeField": true,
        "addClass": true,
        "removeClass": true,
        "clearAllDataFromClass": true,
        "exportClass": false,
        "editClassLevelPermissions": true,
        "editPointerPermissions": true
      }
    },
    "parseServerVersion": "2.2.22"
  }
} create=true, read=true, update=true, delete=true, create=false, read=false, update=false, delete=false, jobs=true, level=true, size=true, order=true, until=true, from=true, immediatePush=true, scheduledPush=false, storedPushData=true, pushAudiences=false, addField=true, removeField=true, addClass=true, removeClass=true, clearAllDataFromClass=true, exportClass=false, editClassLevelPermissions=true, editPointerPermissions=true, parseServerVersion=2.2.22
verbose: REQUEST for [GET] /parse/classes/_Installation: {
  "where": {},
  "limit": 0,
  "count": 1
} method=GET, url=/parse/classes/_Installation, host=localhost:1337, connection=keep-alive, content-length=171, origin=http://localhost:4040, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:4040/apps, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.8, , limit=0, count=1
verbose: REQUEST for [GET] /parse/classes/_User: {
  "where": {},
  "limit": 0,
  "count": 1
} method=GET, url=/parse/classes/_User, host=localhost:1337, connection=keep-alive, content-length=171, origin=http://localhost:4040, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:4040/apps, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.8, , limit=0, count=1
verbose: RESPONSE from [GET] /parse/classes/_Installation: {
  "response": {
    "results": [],
    "count": 0
  }
} results=[], count=0
verbose: RESPONSE from [GET] /parse/classes/_User: {
  "response": {
    "results": [],
    "count": 0
  }
} results=[], count=0
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
^CTermination signal received. Shutting down.
(node:32517) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
^CTermination signal received. Shutting down.
```

### PR DESCRIPTION
**Pull request by kulshekhar**
Fixes #2875

Currently, express doesn't shut down immediately after receiving SIGINT/SIGTERM if it has client connections that haven't timed out. (This is a [known issue](https://github.com/nodejs/node/issues/2642) with node)

This PR intends to fix this behavior such that parse server will close all open connections and initiate the shutdown process as soon as it receives a SIGINT/SIGTERM signal.

### CODE REVIEW

File: src/cli/parse-server.js [hunk 1]
```diff
@@ -43,8 +47,27 @@ function startServer(options, callback) {
     }
     ParseServer.createLiveQueryServer(liveQueryServer, options.liveQueryServerOptions);
   }
+
+  function initializeConnections(socket) {
+    const socketId = socket.remoteAddress + ':' + socket.remotePort
```
Comment (flovilmart) [inline src/cli/parse-server.js]: Add trailing:

**Comment by flovilmart** [comment]
Awesome!

**Comment by mmarshak** [comment]
@flovilmart I integrated a job scheduler in the same server that Parse server use, I am using Kue-Scheduler. In order to prevent stuck jobs with Kue I had my own code that detect when there is SIGINT/SIGTERM and does a clean shutdown of Kue (radis based connection) by calling -

 Queue.shutdown( shutDownTimout, function(err){
   console.log("Kue Shutdown completed result ", err || "ok" );
   process.exit(0);
} 

Now Parse handing of SIGINT/SIGTERM is independent of Kue handling of shutdown and one can decided to exist earlier before the other. 

It will be very helpful if there was some hook (function) that Parse server will before it actually call process.exit() and allow other connections to close cleanly before Parse call exit().
